version: '3'

services:

  coopdb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mysecret
    image: mongo:4-bionic
    container_name: coopdb
    volumes:
      - coopdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - coopnet

  coopapp:
    environment:
      - NODE_ENV=development
      - PORTHTTP=3000
      - PORTWS=3001
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: coopapp
    depends_on:
      - coopdb
    command: /bin/sh -c 'npm i && npm run debug'
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - coopnet

volumes:
  coopdata:

networks:
  coopnet:
